name: Autoformat source code
on:
  pull_request:
    branches: [main]

env:
  RUFF_OPTS: "format"

jobs:
  ruff_format:
    runs-on: ubuntu-latest
    name: Format source code with ruff
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Format files in 3rd_party/gnn
      uses: astral-sh/ruff-action@v3
      with:
        src: "./3rd_party/gnn"
        args: ${{ env.RUFF_OPTS }}
    - name: Format files in examples
      uses: astral-sh/ruff-action@v3
      with:
        src: "./examples"
        args: ${{ env.RUFF_OPTS }}
    - name: Format files in tests
      uses: astral-sh/ruff-action@v3
      with:
        src: "./tests"
        args: ${{ env.RUFF_OPTS }}
    - name: Commit formatted files
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "Format code with ruff"
        commit_options: '--no-verify --signoff'
        file_pattern: '*.py'
